### ISSUE TITLE
inventory describes mounts but not checked/enforced

### ISSUE THREAD

**Issue by martinetd** [open-io/ansible-playbook-openio-deployment#41]
Hello,

Since the inventory.yml describes mount points with partitions I was assuming the playbook would format them for me, or at least complain that they weren't mounted if not.

Please either add a comment in inventory.yml or make ansible ensure the mounts in that file make sense with what is actually configured on the servers.

Thanks,
.. 
Dominique

**Comment by cdelgehier** [comment]
Hello,

You can enable the matching of declarations and mounts by assigning the value `true` [here](https://github.com/open-io/ansible-playbook-openio-deployment/blob/19.04/products/sds/inventory.yml#L44)

Thanks,
Cédric

**Comment by martinetd** [comment]
aaah! If it's just a check why is it not enabled in the example config?

Maybe comment out the "partition" settings of each mountpoint if you want people to explicitly set something, but I was really surprised after configuring the partitions properly that they didn't get used at all. Having explicit settings that aren't used in the default config is really odd.

Thanks,
